// <auto-generated />
using System;
using DaLatFood.Migrator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaLatFood.Migrator.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20230401150736_FK_Product2FileEntryCollection")]
    partial class FK_Product2FileEntryCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaLatFood.Domain.File.Entity.FileEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FileEntryCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileEntryCollectionId");

                    b.ToTable("FileEntry", "FileSchema");
                });

            modelBuilder.Entity("DaLatFood.Domain.File.Entity.FileEntryCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileEntryCollection", "FileSchema");
                });

            modelBuilder.Entity("DaLatFood.Domain.Product.Entity.Production", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FileEntryCollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileEntryCollectionId");

                    b.ToTable("Product", "ProductSchema");
                });

            modelBuilder.Entity("DaLatFood.Domain.File.Entity.FileEntry", b =>
                {
                    b.HasOne("DaLatFood.Domain.File.Entity.FileEntryCollection", null)
                        .WithMany("FileEntryEntries")
                        .HasForeignKey("FileEntryCollectionId");
                });

            modelBuilder.Entity("DaLatFood.Domain.Product.Entity.Production", b =>
                {
                    b.HasOne("DaLatFood.Domain.File.Entity.FileEntryCollection", "FileEntryCollection")
                        .WithMany()
                        .HasForeignKey("FileEntryCollectionId");

                    b.Navigation("FileEntryCollection");
                });

            modelBuilder.Entity("DaLatFood.Domain.File.Entity.FileEntryCollection", b =>
                {
                    b.Navigation("FileEntryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
